---
title: "specifying-manual-cut-scores"
description: >
  Specify manusal cut scores
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{specifying-manual-cut-scores}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = F)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "vignettes",
  out.width = "100%"
)

options(tibble.print_min = 5, tibble.print_max = 5)
```

# Specification of Manual Cut Scores

## Overview

How to specify manual cuts


## Fit Embeded Standard Setting

```{r eval = T}
library(EmStanS)
```

```{r eval = T}
set.seed(100)
# data <- read.csv(filePath)
fake_data <- genFakeDataSet(ngca = 3, 
               cor_val = 0.2,
               n = 30,
               nlevel = 3,
               ntable = 5,
               npanelist = 5,
               sdinp = 1,
               ecinp = 0,
               100,300)



fake_data

# Or you can use your own data structured by the following table.
```

```{r eval = T}
res <- emstans(data = fake_data,
               grade = c(1,2),
               targets = "ALD",
               WESS = T,
               gamest = F,
               median = "modal",
               loc = "Loc_RP50",
               domain = "GCA")

```


## Update with manual cut scores

```{r eval = T}
extract(res, "cutscore")
```

```{r eval = T}
new_res <- update(res, "M1-All" = c(150, 200))
```


## Report

```{r eval = T}
report(new_res, what = "all")
```

