#' @include 0_import.r
NULL

#' read_data
#'
#' @param filePath a character for a file path.
#' @param sheets_name a list for names of excel sheets
#' @return a named list containing standard setting information (excel data with 5 sheets.)
#' @examples
#' \dontrun{
#' filePath <- "data/freq_data.xlsx"
#' imported_data <- read_data(filePath)
#' }

read_data <- function(filePath, sheets_name) {
  # filePath = path;
  imprt_data_12 <-
    sheets_name[1:2] %>%
    map(read_excel, path = filePath)

  imprt_data_3 <-
    sheets_name[3] %>%
    map(read_excel, path = filePath, col_types = 'text')

  imprt_data_4 <-
    sheets_name[4] %>%
    map(read_excel, path = filePath) %>%
    map(., ~ .x %>% mutate(Item_ID = as.character(Item_ID)))

  imprt_data_5 <-
    sheets_name[5] %>%
    map(read_excel, path = filePath)

  imprt_data <- append(imprt_data_12, imprt_data_3)
  imprt_data <- append(imprt_data, imprt_data_4)
  imprt_data <- append(imprt_data, imprt_data_5)

  imprt_data <-
    imprt_data %>%
    set_names(nm = c("setup","panelist","rating","item_data","examinee_data"))

  return(imprt_data)
}

#' data_ready
#'
#' @param imprt_data a list of imported data using \code{\link{read_data}}
#' @return a list of the data ready for the analysis.
#' @examples
#' \dontrun{
#' require(embededss)
#' filePath <- "data/freq_data.xlsx"
#' imported_data <- read_data(filePath)
#' data_list <- data_ready(imported_data)
#' }

data_ready <- function(imprt_data) { # imprtData = imprt_data

  # IMPORTANT ------------------------------------
  # DATA MUST be in order: setup / panelist / rating / item meta data / examinee data
  # ----------------------------------------------

  setup_data    <- dataReady_setup(imprt_data)
  panelist_data <- dataReady_panelist(imprt_data)
  rating_data   <- dataReady_rating(imprt_data)
  item_data     <- dataReady_itemdata(imprt_data)
  examinee_data <- dataReady_examineedata(imprt_data)

  res <- list(
    setup_data    = setup_data,
    panelist_data = panelist_data,
    rating_data   = rating_data,
    item_data     = item_data,
    examinee_data = examinee_data)

  return(res)
}


#' get_data_info
#'
#' @param data_list a list of prepared data that is generated by \code{\link{data_ready}}
#' @param ... input information for ESS analysis including gca, ald, location, WESS, gamest, domain, select_domain. Those come from the server inputs.
#' @return a list containing all the information necessary for ESS estimation.
#' @examples
#' \dontrun{
#' require(embededss)
#' filePath <- "data/freq_data.xlsx"
#' imported_data <- read_data(filePath)
#' data_list <- data_ready(imported_data)
#' data_information <- get_data_info(data_list, grade = c("M3"), ald = "ALD", location = "Loc_RP60", wess = F, modal = F, threshold = F)
#'
#' }

get_data_info <- function(data_list, ...){

  information <- list()
  inputs <- list(...)
  # inputs <- list(gca = input$tests,
  #                ald = "ALD",
  #                location = input$loc,
  #                WESS = input$WESS,
  #                gamest = input$gamest,
  #                domain  = input$domain,
  #                select_domain = input$select_domain,
  #                modal = F)
  names(inputs) <- tolower(names(inputs))

  setup_data    <- data_list$setup_data
  panelist_data <- data_list$panelist_data
  rating_data   <- data_list$rating_data
  item_data     <- data_list$item_data

  if(sum(data_list$examinee_data == -999) != 0) {
    if("GCA" %in% inputs$domain & length(inputs$domain) == 1) {

      examinee_data <- data_list$examinee_data %>%
        mutate(GCA = paste(GCA, "All", sep = "-"))

      GCA_order <- examinee_data$GCA

    } else if("Domain" %in% inputs$domain & length(inputs$domain) == 1) {

      temp1 <-
        item_data %>%
        select(GCA, Domain) %>%
        arrange(GCA, Domain) %>%
        distinct(GCA, Domain)

      examinee_data <-
        data_list$examinee_data %>%
        left_join(temp1, by = c("GCA")) %>%
        mutate(GCA = paste(GCA, Domain, sep = "-")) %>%
        select(-Domain)

      GCA_order <- examinee_data$GCA

    } else if(length(inputs$domain) == 2) {

      gca_ID <- tibble(GCA = levels(item_data[["GCA"]]), Domain = 'All')
      gca_ID$GCA <- factor(gca_ID$GCA, levels = gca_ID$GCA)

      temp1 <-
        item_data %>%
        select(GCA, Domain) %>%
        arrange(GCA, Domain) %>%
        distinct(GCA, Domain) %>%
        bind_rows(gca_ID, .) %>%
        arrange(GCA)

      examinee_data <-
        data_list$examinee_data %>%
        left_join(temp1, by = c("GCA")) %>%
        mutate(GCA = paste(GCA, Domain, sep = "-")) %>%
        select(-Domain)

      GCA_order <- examinee_data$GCA

    } else {
      examinee_data <- data_list$examinee_data
      GCA_order <- examinee_data$GCA
    }

  } else {

    if("GCA" %in% inputs$domain & length(inputs$domain) == 1) {

      examinee_data <- data_list$examinee_data %>%
        mutate(GCA = paste(GCA, "All", sep = "-"))

      GCA_order <- unique(examinee_data$GCA)

    } else if("Domain" %in% inputs$domain & length(inputs$domain) == 1) {

      temp1 <-
        item_data %>%
        select(GCA, Domain) %>%
        arrange(GCA, Domain) %>%
        distinct(GCA, Domain)

      examinee_data <-
        examinee_data %>%
        left_join(temp1, by = c("GCA")) %>%
        mutate(GCA = paste(GCA, Domain, sep = "-")) %>%
        select(-Domain)

      GCA_order <- unique(examinee_data$GCA)

    } else if(length(inputs$domain) == 2) {

      gca_ID <- tibble(GCA = levels(item_data[["GCA"]]), Domain = 'All')
      gca_ID$GCA <- factor(gca_ID$GCA, levels = gca_ID$GCA)

      temp1 <-
        item_data %>%
        select(GCA, Domain) %>%
        arrange(GCA, Domain) %>%
        distinct(GCA, Domain) %>%
        bind_rows(gca_ID, .) %>%
        arrange(GCA)

      examinee_data <-
        data_list$examinee_data %>%
        left_join(temp1, by = c("GCA")) %>%
        mutate(GCA = paste(GCA, Domain, sep = "-")) %>%
        select(-Domain)

      GCA_order <- unique(examinee_data$GCA)

    } else {
      examinee_data <- data_list$examinee_data
      GCA_order <- unique(examinee_data$GCA)
    }
  }

  data_name <- names(data_list$item_data)
  item_data <- item_data  %>%
    arrange(!!as.name(data_name[1]), !!as.name(inputs$loc))

  if("GCA" %in% inputs$domain) {

    # domain <- ifelse(is.null(inputs$domain), "-", inputs$domain)

    if(length(inputs$domain) > 1) {
      text1 <- glue("paste({paste(inputs$domain, collapse = ',')}, sep = '-')")
      new_GCA <-
        item_data %>%
        select(all_of(inputs$domain), Item_ID) %>%
        filter(Domain %in% inputs[["select_domain"]]) %>%
        mutate(GCA_temp = eval(parse(text = text1))) %>%
        select(GCA_temp, Item_ID)

      GCA_GCA <-
        item_data %>%
        select(GCA, Item_ID) %>%
        mutate(GCA_temp = paste(GCA, "All", sep = '-')) %>%
        select(GCA_temp, Item_ID)

      new_GCA <- bind_rows(GCA_GCA, new_GCA)

    } else {
      new_GCA <-
        item_data %>%
        select(all_of(inputs$domain), Item_ID) %>%
        mutate(GCA_temp = paste(GCA, "All", sep = '-')) %>%
        select(GCA_temp, Item_ID)
    }
  } else {
    new_GCA <-
      item_data %>%
      select(GCA, Domain, Item_ID) %>%
      filter(Domain %in% inputs[["select_domain"]]) %>%
      mutate(GCA_temp = paste(GCA, Domain, sep = '-')) %>%
      select(GCA_temp, Item_ID)
  }

  filtered_data <-
    rating_data %>%
    filter(GCA %in% inputs[["gca"]]) %>%
    left_join(., new_GCA, by = "Item_ID") %>%
    mutate(GCA = GCA_temp) %>%
    select(-GCA_temp) %>%
    mutate(GCA = factor(GCA, levels = GCA_order))

  filtered_data <- filtered_data %>% drop_na()

  id_list <- get_ID(filtered_data)
  SD_data <- get_SD(setup_data, id_list)
  EC_data <- get_EC(setup_data, id_list)

  lv_p <- get_which(remove_blank(names(setup_data)), "LEVELOPTIONS")
  level_nm0 <- setup_data[setup_data$GCA %in% inputs[["gca"]], lv_p]

  information$imported_data <-
    list(
      setup_data     = setup_data,
      panel_data     = panelist_data,
      rating_data    = rating_data,
      item_data      = item_data,
      examinee_data  = examinee_data
    )

  information$base_data <-
    list(
      target_nm     = inputs[["ald"]],
      loc_nm        = inputs[["location"]],
      WESS          = inputs[["wess"]],
      modal         = inputs[["modal"]],
      gamest        = inputs[["gamest"]],
      domain        = inputs[["domain"]],
      select_domain = inputs[["select_domain"]],
      filtered_data = filtered_data
    )

  information$data_ready <-
    list(
      id_list = id_list,
      level_nm = get_lvnm(level_nm0, id_list),
      location_ready = get_location(
        fourth_data = item_data,
        domain = inputs[["domain"]],
        select_domain = inputs[["select_domain"]],
        id_list = id_list,
        locNm = inputs[["location"]]
        ),

      SD_data = SD_data,
      EC_data = EC_data
    )

  .join <- function(x) { # x = a1[[1]]
    GCA_name <- as.character(unique(x$GCA))
    location_info <- information$data_ready$location_ready$bind_loc[[GCA_name]]
    x %>%
      left_join(., location_info[, c("Item_ID","OOD")], by = "Item_ID") %>%
      arrange(OOD) %>%
      select(-OOD)
  }

  information$split_data <-
    filtered_data %>%
    mutate(GCA = factor(GCA, levels = id_list$GCA)) %>%
    group_split(GCA, !!as.name(names(filtered_data)[str_detect(names(filtered_data), "Panel|User")])) %>%
    map(., ~ .join(.x))

  return(information)
}


# Helper functions -----------------------

#' dataReady_setup
dataReady_setup <- function(imprt_data) {

  setup <- imprt_data[[1]]
  setup_name <-names(setup)# c("GCA", "Content Area", "Grade Group", "Number of Tables per group","Level Options", "SD", "EC")
  # names(setup) <- setup_name

  lv_p <- get_which(upper_remove_blank(setup_name), "LEVELOPTIONS")
  level_opt_name <- setup_name[lv_p]

  lv_vec <- map(str_split(setup[[lv_p]], ","), remove_blank_vector)

  lv_vec1 <- lv_vec %>%
    lapply(., function(x) {
      sapply(1:length(x), function(xx) paste0("Level",xx) )}
    ) %>%
    map(., ~paste(.x, collapse = ", ")) %>%
    do.call("rbind", .)

  setup[[level_opt_name]] <-  lv_vec1
  setup$GCA <- factor(setup$GCA, levels = setup$GCA)

  setup_data  <- setup %>% arrange(!!as.name(setup_name[1]))
  return(setup_data)
}
#'
dataReady_panelist <- function(imprt_data) {

  panelist_data <- imprt_data[[2]]
  panelist_data$GCA <- factor(panelist_data$GCA,
                              levels = imprt_data[[1]][["GCA"]])
  return(panelist_data)
}
#'
dataReady_rating <- function(imprt_data) {
  setup <- imprt_data[[1]]
  rating <- imprt_data[[3]]
  itemdata <- imprt_data[[4]]
  itemdata$Item_ID <- as.character(itemdata$Item_ID)
  itemdata$GCA <- factor(itemdata$GCA, levels = imprt_data[[1]][["GCA"]])

  setup_name <- names(setup)
  rating_name <- names(rating)

  rating <-
    left_join(rating,
              itemdata %>% select(Item_ID, starts_with("Order")),
              by = "Item_ID") %>%
    mutate(GCA = factor(GCA, levels = setup$GCA)) %>%
    arrange(GCA, Order_of_Difficulty) %>%
    select(-Order_of_Difficulty)

  ald_p <- get_which(upper_remove_blank(rating_name), "ALD")
  ald_opt_name <- rating_name[ald_p]

  panel_p <- get_which(upper_remove_blank(rating_name), "USE|PANEL")
  lv_p <- get_which(upper_remove_blank(setup_name), "LEVELOPTIONS")
  lv_vec <- map(str_split(setup[[lv_p]], ","), remove_blank_vector)

  new_level_name <-
    rating %>%
    mutate(ALD = remove_blank_vector(ALD)) %>%
    group_split(GCA) %>%
    map(., ~ .x %>% pull(ALD)) %>%
    map2(., lv_vec, ~ paste0("Level", match(.x, .y))) %>%
    unlist(.)

  rating_name[panel_p] <- "Panelist"
  rating[[ald_p]] <- new_level_name
  rating_data <- rating

  return(rating_data)
}
#'
dataReady_itemdata <- function(imprt_data){
  setup <- imprt_data[[1]]
  item_data <- imprt_data[[4]]
  item_data_name <- names(item_data)

  item_data <-
    item_data %>%
    mutate(GCA = factor(GCA, levels = setup$GCA)) %>%
    arrange(!!as.name(item_data_name[1]), Order_of_Difficulty)

  if(sum(str_detect(names(item_data), "^Domain$")) == 1) {
    item_data$Domain <- factor(item_data$Domain)
  }

  return(item_data)
}
#'
dataReady_examineedata <- function(imprt_data){

  examinee <- imprt_data[[5]]
  gca_id <- imprt_data[[1]][1]

  if(dim(examinee)[1] == 0) {
    examinee_data <- bind_cols(score = -999, freq = 1, gca_id)
  } else {
    examinee_data <- suppressMessages(reorganize_examinee(examinee))
    examdt_name <- names(examinee_data)

    gca_p <- get_which(upper_remove_blank(examdt_name), "GRADE|GCA")

    names(examinee_data)[gca_p] <- "GCA"
    examinee_data <- examinee_data %>% arrange(GCA)
  }

  if(length(examinee_data[[3]]) != length(gca_id)) {

    dummy_data <- bind_cols(score = -999, freq = 1, gca_id)
    dummy_data <- dummy_data %>% filter(!GCA %in% examinee_data[[3]])

    examinee_data <- bind_rows(examinee_data, dummy_data) %>%
      mutate(GCA = factor(GCA, levels = pull(gca_id, GCA))) %>%
      arrange(GCA) %>%
      mutate(GCA = as.character(GCA))

  }

  return(examinee_data)
}

get_which <- function(inp, char_match, add_position = 0) {
  which(str_detect(inp, char_match)) + add_position
}

remove_blank_vector <- function(inpData) {
  inpData %>% stri_replace_all_charclass(., "\\p{WHITE_SPACE}", "")
}
#'
upper_remove_blank <- function(vec){
  toupper(remove_blank_vector(vec))
}
#' remove_blank
remove_blank <- function(inp_data) {
  vec <- inp_data %>% stri_replace_all_charclass(., "\\p{WHITE_SPACE}", "")
  vec <- toupper(vec)
  return(vec)
}

#' reorganize_examinee
reorganize_examinee <- function(inp_data){
  if(sum(str_detect(toupper(names(inp_data)), toupper("freq"))) == 0){
    return(inp_data)
  } else {
    inpdata_reorg <- vector("list", ncol(inp_data))

    for(i in 1:ncol(inp_data)) {
      if(sum(is.na(inp_data[i])) == nrow(inp_data)){
        next
      }
      inpdata_reorg[[i]] <- inp_data[i]
    }
    inpdata_reorg <- inpdata_reorg %>% bind_cols()

    inpdata_reorg <- lapply(1:(ncol(inpdata_reorg)/3), function(i) {
      ii = 1 + (i - 1)*3
      iii = ii + 2
      inpdata_reorg[,ii:iii] %>% drop_na() %>%
        set_names(., nm = c("score", "freq","GCA"))
    })

    inpdata_reorg <- do.call('rbind',inpdata_reorg)

    return(inpdata_reorg)
  }
}
#' get_ID
get_ID <- function(filtered_data) {

  filter_name <- names(filtered_data)

  GCAID <- filtered_data %>% distinct(GCA) %>% arrange(GCA) %>% pull() %>% as.character()
  TableID <- filtered_data %>% distinct(GCA, Table) %>% arrange(GCA)

  Table_n <- TableID %>% group_by(GCA) %>% count() %>% pull(n)

  p1 <- as.name(filter_name[str_detect(filter_name, "Panel|User")])

  UserID <- filtered_data %>% distinct(GCA, Table, !!p1) %>% arrange(GCA)
  names(UserID) <- c("GCA", "Table", "User")

  out <- list(GCA = GCAID,
              Table = TableID,
              Table_n = Table_n,
              PanelID = UserID)

  return(out)
}
#' get_SD
get_SD <- function(setup_data, id_list){

  combined_id <- id_list$GCA
  GCA_id <- str_split(id_list$GCA, "-", simplify = T)[,1]

  SD_data =
    tryCatch({

      a1 <- data.frame(GCA = GCA_id) %>%
        left_join(., setup_data, by = "GCA") %>%
        mutate(GCA = combined_id) %>% pull(SD)

      a1[which(is.na(a1))] <- 1
      a1
    },
    error = function(e) 1
    )

  SD_data <- data.frame(GCAid = combined_id, SD = SD_data)
}

#' get_EC
get_EC <- function(setup_data, id_list){

  combined_id <- id_list$GCA
  GCA_id <- str_split(id_list$GCA, "-", simplify = T)[,1]

  EC_data =
    tryCatch({
      a1 <- data.frame(GCA = GCA_id) %>%
        left_join(., setup_data, by = "GCA") %>%
        mutate(GCA = combined_id) %>%
        select(contains("EC")) %>%
        pull()
      a1[which(is.na(a1))] <- 0
      a1
    },
    error = function(e) 0
    )

  EC_data <- data.frame(GCAid = id_list$GCA, EC = EC_data)
}

#' get_lvnm
get_lvnm <- function(inp_data, id_list){
  # inp_data = level_nm0; id_list

  combined_id <- id_list$GCA
  combined_df <- str_split(combined_id, "-", simplify = T)
  GCA_id <- unique(combined_df[,1])

  .get_lvnm <-
    function(inp_data) {
      lvnm <-
        inp_data %>%
        str_split(., ",", simplify = T) %>%
        stri_replace_all_charclass(.,"\\p{WHITE_SPACE}", "")

      return(lvnm)
    }

  temp1 <- apply(inp_data, 1, .get_lvnm) %>%
    data.frame() %>%
    set_names(., nm = GCA_id) %>%
    t() %>%
    data.frame() %>%
    set_names(paste0("y",1:ncol(.))) %>%
    data.frame(., X1 = rownames(.))

  out_df <- data.frame(combined_df) %>%
    set_names(nm = paste0("X", 1:ncol(combined_df))) %>%
    left_join(., temp1, by = "X1")


  text1 <- glue("paste({paste0('X',1:ncol(combined_df), collapse = ',' )}, sep = '-')")
  out_df <-
    out_df %>%
    mutate(GCA_temp = eval(parse(text = text1))) %>%
    mutate(X1 = GCA_temp) %>%
    select(X1, names(temp1)[1:(length(names(temp1))-1)])

  GCAId <- out_df[["X1"]]

  out_df <- data.frame(t(out_df))
  out_df <- data.frame(out_df[-1 , ])

  colnames(out_df) <- GCAId

  out_df
}
#' get_location
get_location <- function(fourth_data, domain, select_domain, id_list, locNm){

  combined_id <- id_list$GCA
  combined_df <- str_split(combined_id, "-", simplify = T)
  GCA_id <- unique(combined_df[,1])

  if("GCA" %in% domain) {
    if(length(domain) > 1) {
      text1 <- glue("paste({paste(domain, collapse = ',')}, sep = '-')")
      dataUsed <-
        fourth_data %>%
        mutate(GCA_temp0 = eval(parse(text = text1)), .before = GCA) %>%
        filter(GCA %in% GCA_id)

      GCA_GCA <-
        fourth_data %>%
        mutate(GCA_temp0 = paste(GCA, "All", sep = '-'), .before = GCA) %>%
        filter(GCA %in% GCA_id)

      dataUsed <- bind_rows(GCA_GCA, dataUsed) %>% arrange(GCA)
      select_domain <- c("All",select_domain)

    } else {
      dataUsed <-
        fourth_data %>%
        mutate(GCA_temp0 = paste(GCA, "All", sep = '-'), .before = GCA) %>%
        filter(GCA %in% GCA_id)
    }
  } else {
    dataUsed <-
      fourth_data %>%
      mutate(GCA_temp0 = paste(GCA, Domain, sep = '-'), .before = GCA) %>%
      filter(GCA %in% GCA_id)
  }

  if(!is.null(select_domain)) {
    dataUsed <- dataUsed %>%
      mutate(GCA_temp = GCA_temp0) %>%
      separate(GCA_temp0, c("a1","a2"), "-") %>%
      filter(a2 %in% select_domain)
  } else {
    dataUsed <- dataUsed %>%
      mutate(GCA_temp = GCA_temp0)

  }

  GCAId <- combined_id

  location <-
    dataUsed %>%
    mutate(GCA_temp = factor(GCA_temp, levels = GCAId)) %>%
    group_split(GCA_temp) %>%
    map(., ~ .x %>%
          select(GCA_temp, Item_ID, all_of(locNm)) %>%
          rename("GCA" = "GCA_temp"))

  names(location) <- map(location, ~ unique(.x[[1]])) %>% unlist()

  bind_loc <-
    location %>%
    map(., ~ .x %>% arrange(!!as.name(locNm)) %>%
          mutate(OOD = 1:nrow(.)) %>%
          select(-c(1))
    )

  return(list(location = location, bind_loc = bind_loc))
}

#' pull_unique
pull_unique <- function(inpData, colNum) {
  inpData %>% pull(colNum) %>% unique()
}

#' factor_arrange
factor_arrange <- function(inpdata, information ){
  flevels <- information$data_ready$id_list$GCA
  inpdata %>%
    mutate(GCA = factor(GCA, levels = flevels)) %>%
    arrange(GCA)

}
