#' @include 1_data_ready.r
NULL

#' Generate item distribution plots
#'
#' @param information a list of data generated by \code{\link{get_data_info}}
#' @param x_name a character for x-axis title
#' @param x_name a character for y-axis title
#' @param font_size an integer for font size of plot
#' @return a list of item distribution plots for each GCA
plot_dist_items <- function(information, x_name = "", y_name = "", font_size = 16) {

  item_data <- information$imported_data$item_data
  if("Domain" %in% names(item_data)){
    item_data_0 <- item_data %>% select(GCA, Domain, Item_ID) %>%
      rename(
        "Grade" = "GCA",
        "Domain1" = "Domain")
  } else {
    item_data_0 <- item_data %>% select(GCA,  Item_ID) %>%
      mutate(Domain1 = "All") %>%
      rename(
        "Grade" = "GCA")
  }

  ald <- information$base_data$target_nm
  locnm <- information$base_data$loc_nm
  filtered_data <- information$base_data$filtered_data
  location_data <- information$data_ready$location_ready$location

  combined_data <-
    filtered_data %>%
    left_join(., bind_rows(location_data), by = c("GCA", "Item_ID")) %>%
    mutate(GCA_temp = GCA, .before = "Subject") %>%
    separate(GCA_temp, c("Grade", "Domain"), "-") %>%
    left_join(., item_data_0, by = c("Grade", "Item_ID")) %>%
    mutate(Domain = Domain1) %>%
    select(!Domain1) %>%
    filter(Grade != "All") %>%
    mutate(GCA = paste(Grade, Domain, sep = "-"))


  subject_inp <- combined_data %>% group_split(Grade)
  p_list <- vector("list", length(subject_inp))
  for(i in 1:length(subject_inp)) {
    subject_data <- subject_inp[[i]]
    subscore_data <-
      subject_data %>%
      group_split(GCA) %>%
      bind_rows()

    temp_data <-
      subject_data %>%
      mutate(GCA = "All") %>%
      bind_rows(subscore_data)

    gca_number <- length(unique(temp_data[["GCA"]]))
    shapes <- c(15:24, 1:14)

    # plots
    p_list[[i]] <-
      temp_data %>%
      ggplot() +
      geom_point(
        aes(x = !!as.name(locnm), y = !!as.name(ald),
                   shape = !!as.name("GCA"),
                   colour = !!as.name("GCA")
        ),
        size = rel(2),
        alpha = .6,
        position = position_dodge(width = 0.4)
      ) +
      labs(y = y_name, x = x_name) +
      scale_shape_manual(name = NULL, values = shapes[1:gca_number]) +
      scale_color_brewer(name = NULL, palette = "Set1") +
      guides(
        shape = guide_legend(override.aes = list(size = rep(3)))
      ) +
      theme_bw(base_size = font_size) +
      theme(
        plot.margin = unit(c(1,1,1,1), "cm"),
        legend.position = 'bottom',
        legend.margin = margin(0, 0, 0, 0),
        legend.text= element_text(face='bold',
                                  color='black',
                                  size = rel(0.6))
      )
  }

  p_list
}


