#' @include 1_data_ready.r
NULL

#' ESS analysis for individual panelists
#'
#' @param information a list of data generated by \code{\link{get_data_info}}
#' @return a list of data for each panelist about ESS results.
gen_tab0 <- function(information) {
  #
  tab0 <- list()

  if(F) {

    estCutScore(information$split_data[[1]], information)

  }
  est_cutscore <-
    information$split_data %>%
    map(., ~ estCutScore(.x, information)) %>%
    set_names(.,
              nm = information$data_ready$id_list[["PanelID"]] %>%
                filter(GCA %in% information$data_ready$id_list$GCA) %>%
                mutate(User = paste0(GCA, "-", User)) %>%
                pull(3) %>% unique()
    )

  tab0$est_cs <- map(est_cutscore, ~ .x$est_cs)
  tab0$est_cp <- map(est_cutscore, ~ .x$est_cp)
  tab0$selected_CP <- map(est_cutscore, ~ .x$selected_CP)
  tab0$selected_CS <- map(est_cutscore, ~ round(.x$selected_CS,4))
  tab0$selected_weights <- map(est_cutscore, ~ round(.x$selected_weights,4))

  return(tab0)
}


# Helper function ---------------------------

#' Estimate the cut score for each data
estCutScore <- function(inp_data, information, digits = 2) {
  # inp_data = information$split_data[[1]]; digits = 2

  GCA_data <- inp_data
  need_data <- data_prep(GCA_data, information)

  data_1   = need_data$data_1
  level_nm = need_data$level_nm
  test_id  = need_data$test_id
  location = need_data$location
  bind_loc = need_data$bind_loc

  locnm <- names(location)[3]
  ald_vector <- remove_blank_vector(data_1 %>% pull(ALD) )
  lv_vector <- remove_blank_vector(level_nm)

  SD_inp <-
    information$data_ready$SD_data %>%
    filter(GCAid == test_id) %>%
    pull(SD)

  EC_inp <-
    information$data_ready$EC_data %>%
    filter(GCAid == test_id) %>%
    pull(EC)

  cut_scores <- runESS(inp_data, location, length(lv_vector), EC = EC_inp)

  cut_scores <-
    cut_scores %>%
    mutate_at(vars(matches("_W$")), ~ .x /SD_inp) %>%
    mutate_all(round, digits)

  cut_point  <- cal_minp(data_inp = cut_scores)

  gam_est <- splineFit(cut_scores %>% mutate(!!locnm := location[[locnm]]))

  gam_res <- extractgam(gam_est)
  cut_point <- append(cut_point, gam_res[["scp"]])

  selected_CP <- select_cp(cut_point, cut_scores, information$base_data$WESS,information$base_data$gamest)

  selected_CS <- select_cs(selected_CP, gam_res, location, information$base_data$WESS, information$base_data$gamest)

  selected_weights <- select_weight(selected_CP, gam_res,cut_scores, information$base_data$gamest)

  data_2 <- left_join(data_1, bind_loc, by = "Item_ID")
  data_2 <-
    cut_scores %>%
    bind_cols(data_2, .) %>%
    relocate(., OOD, !!as.name(locnm), .after = Item_ID)

  cor_inc <- getCor(inp_data, data_2, selected_CP, lv_vector, locnm, ald_vector)

  data2 <-
    data_2 %>%
    mutate(Operational_Lv = cor_inc[[2]],
           Correlation = cor_inc[[1]])

  o <- list(est_cs = data2,
            est_cp = cut_point,
            selected_CP = selected_CP,
            selected_CS = selected_CS,
            selected_weights = selected_weights,
            gam_est = gam_est)
  return(o)
}

#' Calculate the minimun cut scores and cut point.
#'
cal_minp <- function(data_inp) {
  est_lev <- data_inp
  minimun_points <-
    foreach(el = 1:ncol(est_lev)) %do% {
      # el = 1
      which(est_lev[el] == min(est_lev[el]))
    }

  o.ver <- matrix(
    unlist(expand.grid(minimun_points[1:(length(minimun_points)/2)])),
    ncol = (length(minimun_points)/2),
    byrow = T
  ) %>%
    data.frame(.) %>%
    set_names(.,
              names(est_lev)[1:(length(est_lev)/2)])
  w.ver <- matrix(
    unlist(
      expand.grid(
        minimun_points[(length(minimun_points)/2 + 1):length(minimun_points)]
      )
    ),
    ncol = (length(minimun_points)/2),
    byrow = T
  ) %>%
    data.frame(.) %>%
    set_names(.,
              names(est_lev)[
                (length(est_lev)/2 + 1):length(est_lev)
              ]
    )

  return(list(default = o.ver, weight = w.ver))
}

#' Select the minimun point and cut score
#'
select_cp <- function(cut_point, est_cutscore, WESS, gamest){
  # est_cutscore=cut_scores
  # WESS=information$base_data$WESS
  # gamest=information$base_data$gamest
  level_names <- map(cut_point, names)
  l_names <- level_names[["default"]]
  w_names <- level_names[["weight"]]

  data_use_1 <- est_cutscore

  if(!gamest) {
    if(WESS){
      cut_point <- cut_point[["weight"]]
    } else{
      cut_point <- cut_point[["default"]]
    }

    cut_candi <- cut_point

    ppp <-
      foreach(ii = 1:ncol(cut_candi), .combine = 'c') %do% {
        # ii <- 1
        li <- l_names[ii]
        wi <-  w_names[ii]
        cp1 <- unique(unlist(cut_candi[,ii]))

        pp <-
          data_use_1 %>%
          slice(cp1) %>%
          arrange(!!as.name(wi), !!as.name(li)) %>%
          slice(1) %>%
          select(all_of(li), all_of(wi)) %>% data.frame() %>%
          unname() %>% unlist()

        which( data_use_1[[li]] ==  pp[1] & data_use_1[[wi]] ==  pp[2])[1]

      }
  } else {

    if(WESS){
      ppp <- unlist(cut_point[["weight_gam"]])
    } else{
      ppp <- unlist(cut_point[["default_gam"]])
    }
  }
  return(ppp = ppp)
}
#'
select_cs <- function(selected_CP, gam_res, location, WESS, gamest) {

  est_cut_score <- if(gamest) {
    if(WESS) {
      unlist(gam_res$cp$weight_gam)
    } else {
      unlist(gam_res$cp$default_gam)
    }
  } else {
    temp <- location[[3]][selected_CP]
    if(WESS) {
      names(temp) <- paste0(2:(length(temp)+1), "_W")
    } else {
      names(temp) <- paste0(2:(length(temp)+1), "_C")
    }
    temp
  }
  est_cut_score
}
#'
select_weight <- function(selected_CP, gam_res,cut_scores, gamest) {
  # gamest=information$base_data$gamest
  if(!gamest) {
    weights <- cut_scores[selected_CP, ]
    w_pos <- which(str_detect(names(weights), "_W"))
    w_name <- names(weights[ ,w_pos])
    weights <- diag(as.matrix(weights[ ,w_pos]))
    names(weights) <- w_name
  } else {
    weights <- unlist(gam_res$gam.cs$weight_gam_cs)
  }

  return(weights)
}

#' data_prep
data_prep <- function(inp_data, information){
  # inp_data = GCA_data; information
  loc_inf <- information$data_ready$location_ready
  lv_nm <- information$data_ready$level_nm

  GCAId <- inp_data %>% pull(GCA) %>% unique() %>% as.character()
  level_nm <- lv_nm[, GCAId]

  location <- loc_inf$location[[GCAId]]
  bind_loc <- loc_inf$bind_loc[[GCAId]]

  return(list(
    data_1 = inp_data,
    level_nm = level_nm,
    test_id = GCAId,
    location = location,
    bind_loc = bind_loc))
}

#' Estimate the cut score for one level.
runESS <- function(new_data, location, n_cut, d_alpha = 1, SD = 1, empirical = T, EC = 0) {

  # new_data = inp_data;n_cut = length(lv_vector);d_alpha = 1; SD_inp=1; EC = EC_inp; empirical = T

  new_data <- new_data %>%
    bind_cols(location = location[[3]]) %>%
    select(Item_ID, location, ALD) %>%
    mutate(ALD = as.numeric(str_remove(ALD, "Level")))

  temp1 <- map(2:n_cut,
               ~ essCW(new_data, d_alpha, cut_level = .x, SD, EC = EC, empirical = empirical))

  incon_default <- map(temp1, ~ .x[["incon_default"]]) %>%
    map2(., 2:n_cut,~ .x %>% set_names("cut_score", paste0("L",.y, "_C"),paste0("L",.y,"_W"))) %>%
    bind_cols(.name_repair = "minimal") %>%
    select(-cut_score) %>%
    select(paste0("L",2:n_cut,"_C"), everything()) %>%
    data.frame()

  return(incon_default)
}

# ESS estimate for Count and Weight
essCW <- function(new_data, d_alpha = 1, cut_level = 2, SD = 1, empirical = T, EC = 0) {
  # new_data = new_data_0; cut_level = 2

  new_data$Item_ID <- 1:dim(new_data)[1]

  if(empirical) {

    cut_candi <- new_data$location

  } else {

    if(max(new_data$location) - min(new_data$location) < 10) {
      seq_by = 0.1

      cut_candi <- seq(min(new_data$location), max(new_data$location),
                       by = seq_by)

      cut_candi <- cut_candi - runif(length(cut_candi), -0.1, 0.1)

    } else {

      seq_by = 1

      cut_candi <- seq(min(new_data$location), max(new_data$location),
                       by = seq_by)

      cut_candi <- cut_candi - runif(length(cut_candi), -1, 1)

    }
  }

  cut_candi_id <- rep(1:length(cut_candi), each = dim(new_data)[1])
  cut_candi_list <- rep(cut_candi, each = dim(new_data)[1])

  dt <- data.table(new_data)
  dt.expanded <- dt[ ,list(freq=1:length(cut_candi)), by=names(dt)][order(freq, Item_ID)][ ,freq := NULL]

  dt.expanded[, cut_score := cut_candi_list]
  dt.expanded[, cut_score_id := cut_candi_id]

  incon_default <- data.frame(dt.expanded)

  incon_default <- incon_default %>% data.table() %>% .[, above_ecd := abs(location - cut_score)^d_alpha >= 0]
  incon_default[, below_ecd := abs(location - cut_score)^d_alpha >= 0]

  incon_default[, above_c := location < cut_score & ALD >= cut_level]
  incon_default[, below_c := location >= cut_score & ALD < cut_level]

  incon_default[above_c == T, above_d := abs(location - cut_score)^d_alpha]
  incon_default[below_c == T, below_d := abs(location - cut_score)^d_alpha]

  incon_default <- incon_default[, .(
    above_c = sum(above_c),
    below_c = sum(below_c),
    above_w = sum(above_d, na.rm = T),
    below_w = sum(below_d, na.rm = T)), by=.(cut_score_id)]

  incon_default <- incon_default[, .(
    cut_score = cut_candi,
    counts = above_c + below_c,
    weights = above_w + below_w)
  ]

  return(list(incon_default = incon_default))
}

#' Estimate the correlation
getCor <- function(inp_data, data_2, selected_CP, lv_vector, locnm, ald_vector) {
  # inp_data; data_2; selected_CP; lv_vector; locnm; ald_vector

  op_num <- rep(0, nrow(inp_data))
  op_num[ selected_CP  ] <- 1

  loc_num <- data_2 %>% pull(locnm)

  Operational_name <- get_opname1(inp_data, lv_vector, op_num)

  ald_num <- match(ald_vector, lv_vector)
  olv_num <- match(Operational_name, lv_vector)

  cor_inc <-
    tryCatch({
      cor(ald_num, loc_num)
    },
    warning = function(w) {0},
    error = function(w) {0}
    )


  list(cor_inc, Operational_name)
}

#' get_opname1
get_opname1 <- function(datainp, lvname, opnum){

  efficacy_data_1 <- datainp
  eff_name <- names(efficacy_data_1)
  target_filter = "ALD"

  item_start <- 1
  cut_point <- which(opnum==1)
  num_item <-length(opnum)

  operational_1 <- c(item_start, cut_point, num_item)
  Operational_name <- rep(lvname[length(lvname)], length(opnum))

  for(i in 1:(length(cut_point)+1)){
    # i <- 2
    if(i == (length(cut_point)+1)) {
      Operational_name[operational_1[i]:(operational_1[(i+1)])] <- lvname[i]

    } else {
      Operational_name[operational_1[i]:(operational_1[(i+1)]-1)] <- lvname[i]
    }
  }

  return(Operational_name)
}
